---
- block:
    # https://www.elastic.co/guide/en/graylog/reference/current/rpm.html#rpm-repo
    - name: "Deploy the graylog repo (mirror: {{ repo_graylog__mirror_url }})"
      ansible.builtin.template:
        src: etc/yum.repos.d/graylog.repo.j2
        dest: /etc/yum.repos.d/graylog.repo
        owner: root
        group: root
        mode: "0o644"

  tags:
    - repo_graylog
