---
- tags:
    - repo_remi

  block:
    - name: Deploy /etc/pki/rpm-gpg/RPM-GPG-KEY-remi.el8
      ansible.builtin.copy:
        src: RedHat8/etc/pki/rpm-gpg/RPM-GPG-KEY-remi.el8
        dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-remi.el8
- when: repo_remi__enabled_php_version is defined
  tags:
    - repo_remi

  block:
    - name: Dnf -y module reset php
      ansible.builtin.command: dnf -y module reset php
      register: repo_remi__dnf_module_reset_php_result
      changed_when: '"Nothing to do" not in repo_remi__dnf_module_reset_php_result.stdout'

    - name: Dnf -y module enable php:remi-{{ repo_remi__enabled_php_version }}
      ansible.builtin.command: dnf -y module enable php:remi-{{ repo_remi__enabled_php_version }}
      register: repo_remi__dnf_module_enable_php_result
      changed_when: '"Nothing to do" not in repo_remi__dnf_module_enable_php_result.stdout'

- when: repo_remi__enabled_redis_version is defined
  tags:
    - repo_remi
  block:
    - name: Dnf -y module reset redis
      ansible.builtin.command: dnf -y module reset redis
      register: repo_remi__dnf_module_enable_redis_result
      changed_when: '"Nothing to do" not in repo_remi__dnf_module_enable_redis_result.stdout'

    - name: Dnf -y module enable redis:remi-{{ repo_remi__enabled_redis_version }}
      ansible.builtin.command: dnf -y module enable redis:remi-{{ repo_remi__enabled_redis_version }}
      register: repo_remi__dnf_module_enable_redis_result
      changed_when: '"Nothing to do" not in repo_remi__dnf_module_enable_redis_result.stdout'
