---
- tags:
    - repo_gitlab_ce
  block:
    - name: "Deploy the GitLab CE repo (mirror: {{ repo_gitlab_ce__mirror_url }})"
      ansible.builtin.template:
        src: etc/yum.repos.d/gitlab_gitlab-ce.repo.j2
        dest: /etc/yum.repos.d/gitlab_gitlab-ce.repo
        owner: root
        group: root
        mode: "0o644"
