---
- name: Perform platform/version specific tasks
  ansible.builtin.include_tasks: '{{ lookup("first_found", __task_file) }}'
  vars:
    __task_file:
      files:
        - '{{ ansible_facts["distribution"] }}{{ ansible_facts["distribution_version"] }}.yml'
        - '{{ ansible_facts["distribution"] }}{{ ansible_facts["distribution_major_version"] }}.yml'
        - '{{ ansible_facts["distribution"] }}.yml'
        - '{{ ansible_facts["os_family"] }}{{ ansible_facts["distribution_version"] }}.yml'
        - '{{ ansible_facts["os_family"] }}{{ ansible_facts["distribution_major_version"] }}.yml'
        - '{{ ansible_facts["os_family"] }}.yml'
      paths:
        - "{{ role_path }}/tasks"
  ignore_errors: true # TODO: this probably is a bug in the first_found lookup, according to the doc skip=true should work. else improve the ignore_errors statement
  tags:
    - icingaweb2_module_vspheredb

- tags:
    - icingaweb2_module_vspheredb
  block:
    - name: Add the user icingavspheredb with primary group of icingaweb2
      ansible.builtin.user:
        name: icingavspheredb
        comment: User for icinga-vspheredb.service
        group: icingaweb2
        home: /var/lib/icingavspheredb

    - name: Create directory /usr/share/icingaweb2/modules/vspheredb
      ansible.builtin.file:
        path: /usr/share/icingaweb2/modules/vspheredb
        state: directory
        owner: root
        group: root
        mode: "0o755"

    - name: Curl https://github.com/Icinga/icingaweb2-module-vspheredb/archive/v{{ icingaweb2_module_vspheredb__version }}.tar.gz --output /tmp/ansible.icingaweb2-module-vspheredb-v{{
        icingaweb2_module_vspheredb__version }}.tar.gz
      ansible.builtin.get_url:
        url: https://github.com/Icinga/icingaweb2-module-vspheredb/archive/v{{ icingaweb2_module_vspheredb__version }}.tar.gz
        dest: /tmp/ansible.icingaweb2-module-vspheredb-v{{ icingaweb2_module_vspheredb__version }}.tar.gz
      delegate_to: localhost
      run_once: true
      check_mode: false

    - name: Copy /tmp/ansible.icingaweb2-module-vspheredb-v{{ icingaweb2_module_vspheredb__version }}.tar.gz to /tmp/ansible.icingaweb2-module-vspheredb-v{{ icingaweb2_module_vspheredb__version
        }}.tar.gz
      ansible.builtin.copy:
        src: /tmp/ansible.icingaweb2-module-vspheredb-v{{ icingaweb2_module_vspheredb__version }}.tar.gz
        dest: /tmp/ansible.icingaweb2-module-vspheredb-v{{ icingaweb2_module_vspheredb__version }}.tar.gz

    - name: Unarchive icingaweb2 module vSphereDB
      ansible.builtin.unarchive:
        src: /tmp/ansible.icingaweb2-module-vspheredb-v{{ icingaweb2_module_vspheredb__version }}.tar.gz
        dest: /usr/share/icingaweb2/modules/vspheredb
        remote_src: false
        extra_opts: [--strip-components=1]

    - name: Delete unused file /tmp/ansible.icingaweb2-module-vspheredb-v{{ icingaweb2_module_vspheredb__version }}.tar.gz
      ansible.builtin.file:
        path: /tmp/ansible.icingaweb2-module-vspheredb-v{{ icingaweb2_module_vspheredb__version }}.tar.gz
        state: absent

    - name: Deploy /etc/tmpfiles.d/icinga-vspheredb.conf
      ansible.builtin.template:
        src: etc/tmpfiles.d/icinga-vspheredb.conf.j2
        dest: /etc/tmpfiles.d/icinga-vspheredb.conf
        owner: root
        group: root
        mode: "0o644"

    - name: Cp /usr/share/icingaweb2/modules/vspheredb/contrib/systemd/icinga-vspheredb.service /etc/systemd/system/
      ansible.builtin.copy:
        src: /usr/share/icingaweb2/modules/vspheredb/contrib/systemd/icinga-vspheredb.service
        dest: /etc/systemd/system/
        remote_src: true

    - name: Icingacli module enable vspheredb
      ansible.builtin.shell: icingacli module enable vspheredb
      args:
        executable: /bin/bash
        creates: /etc/icingaweb2/enabledModules/vspheredb

    - name: Mkdir /etc/icingaweb2/modules/vspheredb
      ansible.builtin.file:
        path: /etc/icingaweb2/modules/vspheredb
        state: directory
        owner: apache
        group: icingaweb2
        mode: "0o2770"

    - name: Deploy /etc/icingaweb2/modules/vspheredb/config.ini
      ansible.builtin.template:
        src: etc/icingaweb2/modules/vspheredb/config.ini.j2
        dest: /etc/icingaweb2/modules/vspheredb/config.ini
        owner: apache
        group: icingaweb2
        mode: "0o664"

    - name: Systemd-tmpfiles --create /etc/tmpfiles.d/icinga-vspheredb.conf
      ansible.builtin.command: systemd-tmpfiles --create /etc/tmpfiles.d/icinga-vspheredb.conf

    - name: Systemctl daemon-reload; systemctl enable --now icinga-vspheredb.service
      ansible.builtin.systemd:
        name: icinga-vspheredb.service
        enabled: true
        state: restarted
        daemon_reload: true
