---
- tags:
    - fail2ban

  block:
    - name: Install fail2ban
      ansible.builtin.package:
        name:
          - fail2ban
        state: present

- tags:
    - fail2ban
    - fail2ban:state

  block:
    - name: Systemctl {{ fail2ban__service_enabled | bool | ternary("enable", "disable") }} --now fail2ban.service
      ansible.builtin.systemd:
        name: fail2ban.service
        enabled: "{{ fail2ban__service_enabled }}"
        state: '{{ fail2ban__service_enabled | bool | ternary("started", "stopped") }}'

- tags:
    - fail2ban
  block:
    - name: Deploy actions
      ansible.builtin.template:
        src: etc/fail2ban/action.d/{{ item }}.conf.j2
        dest: /etc/fail2ban/action.d/{{ item }}.conf
        owner: root
        group: root
        mode: "0o644"
      loop:
        - rocketchat
      notify:
        - "fail2ban: restart fail2ban"

    - name: Deploy filters
      ansible.builtin.template:
        src: etc/fail2ban/filter.d/{{ item }}.conf.j2
        dest: /etc/fail2ban/filter.d/{{ item }}.conf
        owner: root
        group: root
        mode: "0o644"
      loop:
        - apache-dos
        - portscan
      notify:
        - "fail2ban: restart fail2ban"

    - name: Deploy /etc/fail2ban/jail.d/z00-defaults.conf
      ansible.builtin.template:
        src: etc/fail2ban/jail.d/z00-defaults.conf.j2
        dest: /etc/fail2ban/jail.d/z00-defaults.conf
        owner: root
        group: root
        mode: "0o640"
      notify:
        - "fail2ban: restart fail2ban"

    - name: "Combined Jails:"
      ansible.builtin.debug:
        var: fail2ban__jails__combined_var

    - name: Remove Jails
      ansible.builtin.file:
        path: /etc/fail2ban/jail.d/z10-{{ item["filename"] }}.conf
        state: absent
      when:
        - item["state"] | d("present") == "absent"
      loop: "{{ fail2ban__jails__combined_var }}"
      notify:
        - "fail2ban: restart fail2ban"

    - name: Create Jails
      ansible.builtin.template:
        src: etc/fail2ban/jail.d/z10-{{ item["template"] }}.conf.j2
        dest: /etc/fail2ban/jail.d/{{ item["filename"] }}.conf
        owner: root
        group: root
        mode: "0o644"
      when:
        - item["state"] | d("present") != "absent"
      loop: "{{ fail2ban__jails__combined_var }}"
      notify:
        - "fail2ban: restart fail2ban"
