---
- name: Install and configure Icinga2 as a agent
  hosts:
    - lfops_icinga2_agent

  roles:
    - role: linuxfabrik.lfops.repo_icinga
      when:
        - ansible_facts["os_family"] != "Windows"
        - not icinga2_agent__skip_repo_icinga | d(false)

    - role: linuxfabrik.lfops.icinga2_agent
