---
- name: Setup automatic update
  hosts:
    - lfops_system_update

  roles:
    - role: linuxfabrik.lfops.yum_utils
      when:
        - ansible_facts["os_family"] == "RedHat"
        - not system_update__skip_yum_utils | d(false)

    - role: linuxfabrik.lfops.at
    - role: linuxfabrik.lfops.mailx

    - role: linuxfabrik.lfops.postfix
      when:
        - not system_update__skip_postfix | d(false)

    - role: linuxfabrik.lfops.mailto_root
      when:
        - not system_update__skip_mailto_root | d(false)

    - role: linuxfabrik.lfops.system_update
