---
- block:
    - name: curl https://repo.linuxfabrik.ch/linuxfabrik.key --output /tmp/ansible.linuxfabrik.key
      ansible.builtin.get_url:
        url: https://repo.linuxfabrik.ch/linuxfabrik.key
        dest: /tmp/ansible.linuxfabrik.key
        mode: "0o644"
      delegate_to: localhost
      changed_when: false # not an actual config change on the server
      check_mode: false # run task even if `--check` is specified

    - name: copy /tmp/ansible.linuxfabrik.key to the remote server
      ansible.builtin.copy:
        src: /tmp/ansible.linuxfabrik.key
        dest: /tmp/ansible.linuxfabrik.key
        mode: "0o644"
      check_mode: false # run task even if `--check` is specified

    - name: rpm --import /tmp/ansible.linuxfabrik.key
      ansible.builtin.rpm_key:
        state: present
        key: /tmp/ansible.linuxfabrik.key

    - name: Deploy /etc/yum.repos.d/linuxfabrik-monitoring-plugins-release.repo
      ansible.builtin.template:
        src: etc/yum.repos.d/linuxfabrik-monitoring-plugins-release.repo.j2
        dest: /etc/yum.repos.d/linuxfabrik-monitoring-plugins-release.repo
        owner: root
        group: root
        mode: "0o644"

  tags:
    - repo_monitoring_plugins
